### ISSUE TITLE
docker-compose.yml improvement

### ISSUE THREAD

**Issue by ZedEugene** [Taraxa-project/taraxa-ops#10]
1) Maybe data mount point must be `- ./data:/opt/taraxa_data/data`
https://github.com/Taraxa-project/taraxa-ops/blob/d0ecf074fc2d7c8146249427b8b2af7766d4e68d/taraxa_compose/docker-compose.yml#L17 
2) Will be nice to add `container_name` for each containers. Auto generated names is `taraxa_compose_node_1 taraxa_compose_status-app_1`

**Comment by rattrap** [comment]
Hey @ZedEugene,

Thanks for this.
The `data` param that you are referring to is actually the name of the volume that we define at the end of the file.

As for the container names, that's deliberate. We don't want these names to conflict with other taraxa containers that we run locally without docker-compose.

We also take advantage of these autogenerated names everywhere in our docs - https://docs.taraxa.io/node-setup/node_address
