### ISSUE TITLE
Wrong link for download docker-compose.yml

### ISSUE THREAD

**Issue by ZedEugene** [Taraxa-project/taraxa-ops#7]
Documentation https://github.com/Taraxa-project/taraxa-ops#running-taraxa-node-with-docker-compose has wrong link for download file "docker-compose.yml" (https://raw.githubusercontent.com/Taraxa-project/taraxa-ops/master/scripts/docker-compose.yml). Maybe must be https://raw.githubusercontent.com/Taraxa-project/taraxa-ops/master/taraxa_compose/docker-compose.yml

**Comment by rattrap** [comment]
Thanks for the report! The main problem here was that downloading just the `docker-compose` file didn't work anymore as we also build the status app inside the compose file
